import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import Ballot from "../components/Ballot";

const Welcome = () => {
  const [ballotsData, setBallotsData] = useState([]);

  const fetchBallotsData = async () => {
    try {
      const res = await fetch("/api/ballots");
      const { items = [] } = await res.json();
      setBallotsData(items);
    } catch (err) {
      console.log("");
    }
  };

  useEffect(() => {
    fetchBallotsData();
  }, []);

  return (
    <div>
      <Head>
        <title>Movie Awards 2021</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {ballotsData.length > 0 && <Ballot ballotsData={ballotsData} />}
      </main>
      <div id="modal-root"></div>
    </div>
  );
};

export default Welcome;
